# Tell Travis CI we are using PHP
language: php

# The platforms you wants to test on
dist: trusty
os:
  - linux

# Define the php versions against we want to test our code
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5

# Encrypted variables
env:
  matrix:
    secure: boP/x3oNeb/ykVxCzIMLrJO3GjdaU6cQjzkVfHH+K7tQDiLRE21C1V9dUqIVhnvWphCk4iU5QmDAIUBbFo7UKO8saHVotgKnBRNd1tvC649F+S2szP+N5nUNOSALWZYTABLRG6aOWBOOjaAWvevjONxbx3SDs1pLFTE1pIUZ8ft6I0GLQQKY3T7oIQN15h72tIIHpmbfavrWYquh5F5LXLvZsW+o4k/O+aQu9zeC2NSxY9bLB4XdgL2vwyOUS93hYDftALCqHEY0wZxTB5QfpfF9Soovey1HUMwmDS0fVil0iHVHmynN0YbpTE27FqUMeklxdUq2i/+a0X2oF4NjNx0CYMcPEeVV2FMEgFQ1zjmc6ADuZaTf4QeSTMhK2ZrBmj1pzwMbh3Pn+LfWm3Y5kEx3MjIT1L+h2NvwXtB1J62wLgx7kCzmsJ5eyJJyrHgimIC9/l8l+AeTayhv0CdPERFnreGgBJn7Nfqx2d3IWq3TJMEPY166KROgjlrYdUcy671sE3qqASiCpgdEyll6060n/QAqG7VclGiMf5OeJwbq/NkXiunIaWwWE1BORFNH1e+u4uuC3D2WxkHryUt57TZz2oaugnN8lo3doJUDG73881GmG65oNjECK7E4uc41KaKrSBTdidOqOxikUWuZDZrV4mQPrYW+0DskSe43Icg=

# We don't want to run linux commands as super user
# false means Travis will run this in a container
sudo: false

# Disable x-debug to speed up things
before_install: phpenv config-rm xdebug.ini

# Install packages those will be required during build
install:
  - composer install --no-interaction

# Prepare test environment
before_script:
  - cp .env.dist .env
  # pass environment variables in travis to the app
  - sed -i "8s/.*/WG_API_KEY=$WG_API_KEY/" .env
  - cat .env

# Run main commands
script:
  - composer test

# Cache folder, you can delete cache from Travis CI web interface
cache:
    directories:
        - vendor
        - $HOME/.composer/cache