# Tell Travis CI we are using PHP
language: php

# The platforms you wants to test on
dist: trusty
os:
  - linux

# Define the php versions against we want to test our code
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5

# Encrypted variables
env:
  matrix:
    secure: "jJeXW5O7rBysw8hs3pPiCrWh1o1Xh4GKQM9Xnpc/50B9u9qtCCjQkbd1kXQn7zNRsTl3muLKZDMtMiTqrN34zvIemgde09Ujmh6q7ylHMAOwrlABvqj3utnOUIIzHbHVnf/ul1dH8vIv3PR+v6ezMVm3h6ecBU49vfm2qg8VK0NLpBmxOaa4stHOsDYHlsGoXVSIty/Ss1PKUFAvzv0/vWPaaJKdLmkKvuWg3ARFJRephhqIaWt7x6FQHe9Ma7AnmT6mSC2DOEGADd5msPEbBKGqczHTOONRd/xiYgz2WOxObxvBoN3SDHwLf/Q1Dhx6K6OsPY0wueAnZeURsIlyevCgVgPd+yhnH4yBN7Gmo80jeYbXIJchTuNnDGWiWTywWK1cTTF3TkbfnmArIeH/dZXrsHjX5JnOHmuV+cIZRd+qftfUaJBgouDeabLz6OHfs4kemo4097Lxc85iCEPqDr/w+ZE1gTi4durOnRaorPoahwSQsIYmqcFWOGtjAC3ga2nrLGvQ8oAnfiSF5b+wYQJb5qFUW6u8R71ZDy2rjvZ2qtFjhmGiOOI5qN78P5sPXRRPQkITkyRZ00NArzpjXg6qz04HbzR2hVnUiwHpuop+Gj7uvnLrmt9Vftv/6ifYD348WhYfBq9ggqZIMAVrquvYmTb9SOt+knp8oTomjPQ="

# We don't want to run linux commands as super user
# false means Travis will run this in a container
sudo: false

# Install packages those will be required during build
install:
  - composer install --no-interaction

# Prepare test environment
before_script:
  ## downloading last codeclimate test report
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # creating .env file
  - cp .env.dist .env
  # pass environment variables in travis to the app
  - sed -i "8s/.*/WG_API_KEY=$WG_API_KEY/" .env

# To manage coverage for CodeClimate
after_script:
- mv tests/_output/coverage.xml clover.xml
- ./cc-test-reporter after-build --coverage-input-type clover --id $COVERAGE_ID --exit-code $TRAVIS_TEST_RESULT

# Run main commands
script:
  - composer test

# Cache folder, you can delete cache from Travis CI web interface
cache:
    directories:
        - vendor
        - $HOME/.composer/cache