language: php

services:
  - redis-server

env:
  global:
    - TEST_COMMAND="./vendor/bin/codecept run unit --no-interaction"
    - TEST_FLAGS=""
    - DEPENDENCIES="cache/predis-adapter"
    - secure: "cGAzQSqrK0lb8zuyvHZui+vlN3hBWt0E4Hbm7DgML/wCiVNRHKHtIPiV5eJ3PhV3hGiochJt650RIGZwiFsm9CE6nc9TSMw0o+B4EWwCMHJX5FCWFgbi7T/D148mJ08Ggyq3g5jII17cmofTczp+GKlRw9tSbyLmn4PeU6SNVQFMqWEkCscvQtmzsDGgyrfpJUwCGsIykljsV3QWahBUS6Cw95nNOFuGB2OEoQKn2w/rXsaPPgX8p2XI6FGxJsqK1GZEineeLuUqVCf/9t2/IZkO0z6iRl1MAxXlOH9HM/QLU/YK9yYdm/7z0fIdwp4XyRTTrq9hi7od2ZR/g26W7jYTaGBDJI5m5HErrxLtpNtadWcg1ayMHgnnjutXKw3Zz3j2azeAioS3vIwT9BBqGGVsac+TZA5U0Q/wMx8ZAztix4hVHcvqVz0YCqdNEfyy0O6Bdh18sSz7QTQiLcp/pxJ82IM4NVxF7mivR2/36Xw9GDZ0vAHDAn61VYEVU1ZrhKGbJh2absIE1+m8ptqx6sB2MYY5BAdFnXQsgXgJ/P0/3PETK2apwcNbpvTFb93A31EujM26igtiI9s/5k7qZ2S7NMIaSSq/kn4AvhYmRJzaLMXb3s8fsb5MazjoFm+x/NDhlSetRz3IQZodkfXBRpJVotooUAQnDnVUt2gNbCY="
    - secure: "PnYQP+zTa43kdgeZM39xfaK8ptIizrwKBRTJNyS+8jpZk+I73/S+mVBoF4W9pRMGk3cz02In3XWLI+rRAaAqEbSoY2H/HRkCG8u06sjz0qDiKX+dEjeCFzo9CYnCNsO7ESWvOlnFys2OztnB9tOTXuCKiA631dDBtsNN0F2p7sy68XOcHuuCqTHYrRUT/YAg0pQJUuDvk6PuIXdne/4xXhV9jSe6DYHujNKe9Dj04fh/o1oZGatK5h9VF5eDw4eClcrhziHd1xRYnW9aiB0Dz8x69b98d1Yx48wCWX2v4RJG9sbpJ1zCVTlcBnoV1F5nkhzxsktIvyZU+KzLr1mYN2rnl8hEFu2+0Q1iyyaW2wp9X36dJ6Qttqbt8amGfXlUygfjYM2srhdXuGEUALNfwyRCCNrVePOaSrkS3yOXWX1r4NiBRoBBzDRaaPspNwlOoSI/YJwKGuUxgz6IdHGwbVWFd7hJwuTULhBIOfVhay7KtNTDoEHqX9nNZs3L4IZTiKeb4KVh1MD3BscRfR2+G3w9o8OcWtlgCA1kKYPNP+Qdxb3y9HRSzmqwvZzfOPoCbqEvs3pKZaIHlPR+mH79ZBRelTyLenZ5EYQzcPQG2zNOBZdV/9pVj9gjub367i6U3/bd388BOfNoTFZp5CjYHs3EKZLFM1bh7JP+HyLTp7w="

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: TEST_FLAGS="-g client -g parser" DEPENDENCIES=""
    - php: 5.5
      env: TEST_FLAGS="-g client -g parser" DEPENDENCIES=""
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: COVERAGE=true TEST_FLAGS="--coverage --coverage-xml"

install:
  - composer install --no-interaction
  - if ! [ -z "$DEPENDENCIES" ]; then composer require ${DEPENDENCIES}; fi;

before_script:
  - cp .env.dist .env
  - sed -i "8s/.*/WG_API_KEY=$WG_API_KEY/" .env
  - if [[ $COVERAGE = true ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ $COVERAGE = true ]]; then chmod +x ./cc-test-reporter; fi
  - if [[ $COVERAGE = true ]]; then ./cc-test-reporter before-build; fi

script:
  - composer validate --strict --no-check-lock
  - $TEST_COMMAND $TEST_FLAGS

after_script:
  - if [[ $COVERAGE = true ]]; then mv tests/_output/coverage.xml clover.xml; fi
  - if [[ $COVERAGE = true ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

cache:
  directories:
    - $HOME/.composer/cache